### ISSUE TITLE
passed my logShout function a function, and it passed

### ISSUE THREAD

**Issue by ksav61** [learn-co-curriculum/javascript-intro-to-functions-lab#15]
Hello, while working on this exercise, I wrote:

`logShout(function) {
console.log(shout)
}
`

and did the same for the logWhisper function.

When I ran the exercise, it said I passed, but the console kicked out some errors about functions and other stuff.  

Can you pass a function another function? That seemed to be the obvious solution to me since we built those other two functions, but I might have done this incorrectly, even though I passed the exercise. 

attached are screenshots of the passing code and the error the console spit out.

<img width="509" alt="screen shot 2016-12-01 at 7 36 12 pm" src="https://cloud.githubusercontent.com/assets/8549456/20820031/d4c11be2-b7fd-11e6-9b93-7dfe8f6d2005.png">
<img width="1131" alt="screen shot 2016-12-01 at 7 36 45 pm" src="https://cloud.githubusercontent.com/assets/8549456/20820032/d4c2710e-b7fd-11e6-8cf9-75d408b9401b.png">

**Comment by lilyxling** [comment]
I had the same issue - please advise.

**Comment by DBRK** [comment]
Also having the same issue what should I do?

**Comment by aturkewi** [comment]
Hey all! These questions are really better suited for the Ask A Question button in Learn. 

It looks like what's happening though is that you are not able to use `function` as a variable name because it is a javascript _keyword_. This means that the Javascript language already has a definition for `function`. 

For the code snippet above, the `shout` function and the `whisper` function are both defined in the same scope as your log function, so you don't need to pass those in as an input. You'd want to do something more like:
```js
function logShout(string){
  console.log(shout(string));
}
```
Because if you want to call the function `shout`, don't forget that you have to follow the function name with `()` _and_ put the input string inside the parenthesis :)

If any of this explanation is confusing though, please feel free to use the Ask A Question button to get further (and much more immediate) clarification :)
