### ISSUE TITLE
Solution Provided does not work as stated

### ISSUE THREAD

**Issue by SamLaSota** [learn-co-curriculum/javascript-intro-to-functions-lab#99]
The solution to the shout function seen below does not pass any tests for me 

function shout(string){
  return string.toUpperCase
}

**Comment by maxwellbenton** [comment]
Hi @SamLaSota, 

Sorry to hear you were having difficulty with this lab, and I hope you were able to find the solution. It looks like `toUpperCase` is missing `()` at the end. Since `.toUpperCase()` is a method (a.k.a a function available to all strings), the `()` is needed. Otherwise, JavaScript will just return the function definition rather than call it. We've recently updated this lesson's instructions to provide more clarity and guidance around solving the last few tests to help future students get through this content.

We apologize for any frustration this may have caused, but we appreciate you taking the time to give us this feedback.

Thank you!
